load(
    "@io_bazel_rules_pex//pex:pex_rules.bzl",
    "pex_binary",
    "pex_library",
    "pex_test",
    "pex_pytest",
)

pex_binary(
    name = "dotm",
    main = "dotm.py",
    srcs = [
        "dotm.py",
        "dotm/config.py",
        "dotm/__main__.py",
        "dotm/cmd/unlink.py",
        "dotm/cmd/link.py",
        "dotm/cmd/__init__.py",
        "dotm/cmd/sync.py",
        "dotm/thirdparty/yaml/cyaml.py",
        "dotm/thirdparty/yaml/events.py",
        "dotm/thirdparty/yaml/emitter.py",
        "dotm/thirdparty/yaml/composer.py",
        "dotm/thirdparty/yaml/reader.py",
        "dotm/thirdparty/yaml/representer.py",
        "dotm/thirdparty/yaml/error.py",
        "dotm/thirdparty/yaml/serializer.py",
        "dotm/thirdparty/yaml/constructor.py",
        "dotm/thirdparty/yaml/dumper.py",
        "dotm/thirdparty/yaml/loader.py",
        "dotm/thirdparty/yaml/nodes.py",
        "dotm/thirdparty/yaml/__init__.py",
        "dotm/thirdparty/yaml/resolver.py",
        "dotm/thirdparty/yaml/tokens.py",
        "dotm/thirdparty/yaml/parser.py",
        "dotm/thirdparty/yaml/scanner.py",
        "dotm/thirdparty/__init__.py",
        "dotm/util.py",
        "dotm/__init__.py",
        "dotm/profiles.py",
        "dotm/modules.py",
    ],
    interpreter = "python3",
)

