export GOPATH=~/go
export PATH=$PATH:$GOPATH/bin
if [ -e /home/raskol/.nix-profile/etc/profile.d/nix.sh ]; then . /home/raskol/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

export USER_ACCESS_TOKEN=$(cat ~/.github_access_token)
