source "$HOME/.antigen/antigen.zsh"

antigen use oh-my-zsh
antigen bundle git
antigen theme robbyrussell
antigen apply

source "$HOME/.dotfiles/bin/sourcefile.zsh"

#export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

if [ -e /home/raskol/.nix-profile/etc/profile.d/nix.sh ]; then . /home/raskol/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

[[ -s "/home/raskol/.gvm/scripts/gvm" ]] && source "/home/raskol/.gvm/scripts/gvm"
