source "$HOME/.antigen/antigen.zsh"

antigen use oh-my-zsh
antigen bundle git
antigen theme robbyrussell
antigen apply

source "$HOME/.dotfiles/bin/sourcefile.zsh"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
